---
- hosts: bootstrap
  become: yes
# variables can be found under group_vars/all/main.yml  
  tasks:
    - name: download kafka, zookeeper
      get_url:
        url: "{{item.url}}"
        dest: "{{item.dest}}"
      with_items:
        #- url: "file:///home/sam/Downloads/{{jetty_file}}"
        # - url: "{{jetty_download_url}}"
        #   dest: "{{cache_dir}}/{{jetty_file}}"
        - url: "{{kafka_download_url}}"
          dest: "{{cache_dir}}/{{kafka_file}}"
        - url: "{{zookeeper_download_url}}"
          dest: "{{cache_dir}}/{{zookeeper_file}}"
        

#    - name: fetch platforms
#      unarchive:
#        src: "{{ item.url }}"
#        #src: "/home/sam/Downloads/jetty-distribution-9.4.19.v20190610.zip"
#        dest: cache/{{item.file}}
#        state: directory
#        creates: cache/{{item.file}}
#        extra_opts: [--strip-components=1]
#        remote_src: yes
#      loop:
#        #- url: "{{ jetty_url }}"
#        - url: "/home/sam/Downloads/jetty-distribution-9.4.19.v20190610.zip"
#          file: jetty


# - name: install_zookeeprs
#   hosts: nomad_clients
#   roles:
#     - zookeeper

- name: install_kafka
  hosts: kafka_brokers
  roles:
    - kafka

- name: install_redis
  hosts: master
  become: yes
  tags:
    - redis
  roles:
    - redis


- name: install_prometheus
  hosts: master
  become: yes
  tags:
    - monitoring
    - prometheus
  roles:
    - monitoring


