all:
  children:
    master:
      hosts:
        localhost:
          ansible_connection: local
          network_interface: lxdbr0
          datacenter: dev
    lxc_containers:
      children:
        consul_servers:
          hosts:
            consul[1:3]:
              type: consul
        nomad_servers:
          hosts:
            nomad-server[1:3]:
              type: server
        nomad_clients:
          hosts:
            nomad-client[1:3]:
              # zookeeper_myid: 
              # broker_id: 
              my_id: [] 
              type: worker
          vars:
            zookeepers: "client.zk-server.service.consul:2181"
        proxy_servers:
          hosts:
            proxy:
              type: proxy
      vars:
        datacenter: dc1
  vars:
    network_interface: eth0
    ansible_connection: lxd
    ansible_python_interpreter: /usr/bin/python3
    datacenter: "dc1"