---
# - name: setup nomad and consul services
# - import_role:
#     name: consul_service

# - import_role:
#     name: nomad_service

- name: copy nomad config
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
  notify: 
    - start nomad

# - name: start nomad
#   service:
#     name: nomad
#     state: restarted
#     enabled: yes

- name: copy consul config
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
  notify: 
    - start consul

- name: create cni bin
  file:
    path: "{{cni_dest}}"
    state: directory
    mode: 755
  
- name: copy cni plugin
  unarchive:
      src: "{{bootstrap_url}}/{{cni_file}}"
      dest: "{{cni_dest}}"
      remote_src: yes 
      mode: "a+rwx" 

# - name: start consul
#   service:
#     name: consul
#     state: restarted
#     enabled: yes